Starting Klippy...
Args: ['klipper/klippy/klippy.py', '-I', 'printer_data/run/klipper.tty', '-a', 'printer_data/run/klipper.sock', 'printer_data/config/printer.cfg', '-l', 'printer_data/logs/klippy.log']
Git version: '?'
Branch: ?
Remote: ?
Tracked URL: ?
CPU: 4 core ?
Python: '3.11.6 (main, Nov  1 2023, 10:18:35) [GCC 12.2.0]'
Start printer at Tue Nov 14 22:11:04 2023 (1699999864.9 96112.6)
Config error
Traceback (most recent call last):
  File "/opt/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/opt/klipper/klippy/klippy.py", line 134, in _read_config
    config = pconfig.read_main_config()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/klipper/klippy/configfile.py", line 281, in read_main_config
    regular_config = self._build_config_wrapper(regular_data, filename)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/klipper/klippy/configfile.py", line 268, in _build_config_wrapper
    self._parse_config(data, filename, fileconfig, set())
  File "/opt/klipper/klippy/configfile.py", line 256, in _parse_config
    self._resolve_include(filename, include_spec, fileconfig,
  File "/opt/klipper/klippy/configfile.py", line 229, in _resolve_include
    raise error("Include file '%s' does not exist" % (include_glob,))
configparser.Error: Include file 'printer_data/config/mainsail.cfg' does not exist
